version: "2"

services:
  db:
    image: docker.io/library/mariadb:10.11.11
    env_file:
      - ./db.env
    volumes:
      - ./db:/var/lib/mysql
      - ../pouet.sql:/docker-entrypoint-initdb.d/pouet.sql
  www:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ..:/var/www/html
      - ../content:/srv/content
      - ./credentials.inc.php:/var/www/html/include_generic/credentials.inc.php
